version: '3'
services:
  db:
    image: mongo:5.0
    ports: 
      - "27017:27017"
    
   
  webapp:
    build: ./web-app
    ports:
      - "6001:6001"
    depends_on:
      - db



  mlclient:
    build: ./machine-learning-client
    ports:
      - "7001:7001"
    environment:
      - PYTHONUNBUFFERED=1

    dns:
      - "8.8.8.8"
    depends_on:
      - db
