version: '3'
services:
  mongodb:
    image: mongo:5.0
    environment:
      - MONGODB_CONNSTRING=mongodb+srv://okkiris:F3iQz3hSCxOwhhOu@cluster0.ubegai3.mongodb.net/?retryWrites=true&w=majority
    ports: 
      - 27018:27018
  webapp:
    build: ./web-app
    ports:
      - "6001:6001"

  mlclient:
    build: ./machine-learning-client
    ports:
      - "7001:7001"
