name: machine learning workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  machinelearningtests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./machine-learning-client
    timeout-minutes: 6
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.8', '3.11']

    steps:
      - name: set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip3 install cmake
          pip install -r requirements.txt
          pip install pytest
      - name: Test with pytest
        run: |
          pytest
